freebsd_instance:
  image_family: freebsd-13-1

build_task:
  upgrade_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - cat /etc/pkg/FreeBSD.conf | sed -e 's/quarterly/latest/' > /usr/local/etc/pkg/repos/FreeBSD.conf
  install_elixir_script:
    - pkg install -y elixir
    - mix local.hex --force
    - mix local.rebar --force
  test_script:
    - mix deps.get
    - mix test
